"""Phase 10.3 — Progressive scoring: item generation tracking and score delta.

Two schema changes:

1. ``items.generation`` (Integer, non-nullable, default 1) — tracks which
   refresh round an item belongs to.  Generation 1 = the first set of items
   generated by the Item-Writer.  When all gen-1 items are exhausted by a
   practitioner, the Item-Writer generates generation 2, and so on.  The
   progressive mastery ceiling formula (1 - 0.5^N) uses the count of
   completed generations as N.

2. ``certification_domain_scores.previous_mastery_score`` (Numeric(4,3),
   nullable) — stores the score from the previous compute so the API can
   return a mastery delta and trend indicator without scanning history rows.

Revision ID: 015
Revises: 014
Create Date: 2026-08-11
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "015"
down_revision: Union[str, None] = "014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── items: add generation column ─────────────────────────────────────────
    op.add_column(
        "items",
        sa.Column(
            "generation",
            sa.Integer,
            nullable=False,
            server_default=sa.text("1"),
            comment="Which refresh round this item belongs to (1-indexed). "
                    "Mastery ceiling = 1 - 0.5^rounds_completed.",
        ),
    )

    # ── certification_domain_scores: add previous_mastery_score column ───────
    op.add_column(
        "certification_domain_scores",
        sa.Column(
            "previous_mastery_score",
            sa.Numeric(4, 3),
            nullable=True,
            comment="The mastery_score from the previous compute cycle, used for "
                    "delta and trend calculation without scanning history rows.",
        ),
    )


def downgrade() -> None:
    op.drop_column("certification_domain_scores", "previous_mastery_score")
    op.drop_column("items", "generation")
